### ISSUE TITLE
Running as one docker compose application

### ISSUE THREAD

**Issue by siredwin** [GoldenThrust/Virtual-Bank#16]
Hello,
How do I run both the api and web part as one application in docker compose file?
I have something like below, but it still won't quite work well on the front part.

```
#version: "3.8"
services:
  db:
      image: postgres:15
      hostname: db
      environment:
        POSTGRES_USER: ${DB_USER}
        POSTGRES_PASSWORD: ${DB_PASSWORD}
        POSTGRES_DB: ${DB_NAME}
      volumes:
        - postgres_data:/var/lib/postgresql/data
      ports:
        - "5432:5432"
      env_file:
        - .env

  redisserver:
      image: redis:7
      hostname: redisserver
      command: redis-server
      ports:
        - "6379:6379"
  
  api:
     build: ./api
     ports:
       - "8000:8000"
     volumes:
       - ./api:/app
     command: python manage.py runserver 0.0.0.0:8000
     depends_on:
       - db
       - redisserver
     env_file:
       - .env   


  web:
     build: ./clients
     ports:
       - "8001:8001"
     volumes:
       - ./clients:/app
     command: python manage.py runserver 0.0.0.0:8001
     depends_on:
       - db
       - redisserver
     env_file:
       - .env  

volumes:
  postgres_data:

```
